### ISSUE TITLE
sql语句无法审核，抛出Incorrect database name '' 错误

### ISSUE THREAD

**Issue by lanyulei** [mysql-inception/inception#38]
下面语句中直接在解释器执行是没问题的， 但是使用inception检查的时候，机会抛出
Incorrect database name ''， 不知道，是哪里的原因，能帮忙看下吗？
sql 语句为：
USE test ;

UPDATE 
  test1 as t1,
  (SELECT 
    id 
  FROM
    `test2` 
  WHERE id = 2) as t2
SET
  `name` = 'lisi' 
WHERE t1.id = t2.id ;

**Comment by mysql-inception** [comment]
有子查询的话，都会有这个问题。目前识别不了子查询中的结果列。
