### ISSUE TITLE
查询osc进度时，inception core dump

### ISSUE THREAD

**Issue by johnliu2008** [mysql-inception/inception#39]
在执行例如inception get osc_percent '*7ED4A8DA0B6686B71BD1371223319D8B97D924D8'命令时，inception进度core dump。以下是gdb输出：

gdb ./mysql/bin/Inception core.11117 

GNU gdb (GDB) Red Hat Enterprise Linux (7.2-60.el6_4.1)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /app/inception/mysql/bin/Inception...(no debugging symbols found)...done.
[New Thread 46959]
[New Thread 11117]
[New Thread 46951]
Missing separate debuginfo for 
Try: yum --disablerepo='*' --enablerepo='*-debug*' install /usr/lib/debug/.build-id/ff/4cbaae51a93124ed31c2b1386ce92ff24aebc3
Reading symbols from /lib64/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Loaded symbols for /lib64/libpthread.so.0
Reading symbols from /lib64/librt.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/librt.so.1
Reading symbols from /lib64/libcrypt.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libcrypt.so.1
Reading symbols from /lib64/libdl.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libdl.so.2
Reading symbols from /usr/lib64/libstdc++.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libstdc++.so.6
Reading symbols from /lib64/libm.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libm.so.6
Reading symbols from /lib64/libgcc_s.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libgcc_s.so.1
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Reading symbols from /lib64/libfreebl3.so...(no debugging symbols found)...done.
Loaded symbols for /lib64/libfreebl3.so
Reading symbols from /lib64/libnss_files.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libnss_files.so.2
Reading symbols from /lib64/libnss_dns.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libnss_dns.so.2
Reading symbols from /lib64/libresolv.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libresolv.so.2
Core was generated by `./mysql/bin/Inception --defaults-file=inc.cnf'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000006128ba in mysql_execute_inception_osc_show(THD*) ()
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.132.el6.x86_64 libgcc-4.4.7-4.el6.x86_64 libstdc++-4.4.7-4.el6.x86_64 nss-softokn-freebl-3.14.3-9.el6.x86_64
(gdb)

**Comment by johnliu2008** [comment]
Version: Inception2.1.49 (Source distribution)

**Comment by johnliu2008** [comment]
可能是当前SQL正在执行时，另外一个会话拿相同的SQL去审核导致的。避免这种情况之后，没再core dump过

**Comment by dikang123** [comment]
@johnliu2008 啥意思，这个core dump本质上不是inception引起的么？

**Comment by johnliu2008** [comment]
恩，本质上不是Inception的BUG。
我估计是Inception为了防止多个会话同时执行相同的SQL导致数据出错，主动core dump的。
我看不懂源码，所以也只是猜测
