### ISSUE TITLE
没有备份

### ISSUE THREAD

**Issue by benben17** [mysql-inception/inception#50]
inception 的备份信息已经配置如下：
inception_remote_system_password=inception_web
inception_remote_system_user=inception_web
inception_remote_backup_port=8801
inception_remote_backup_host=10.10.xx.xx

通过python 执行命令返回如下。
但是在对应的备份数据库上没有看到 192_168_27_54_3331_DB_CAMPUS_V2这个备份数据库

['ID', 'stage', 'errlevel', 'stagestatus', 'errormessage', 'SQL', 'Affected_rows', 'sequence', 'backup_dbname', 'execute_time', 'sqlsha1']
((1L, 'RERUN', 0L, 'Execute Successfully', 'None', 'use DB_CAMPUS_V2', 0L, "'1511160402_12233_0'", 'None', '0.010', ''), (2L, 'EXECUTED', 0L, 'Execute Successfully', 'None', 'insert into tmp_table(resume_id,wish_id,CR_RESUME_ID) values(211,223,223)', 1L, "'1511160402_12233_1'", '192_168_27_54_3331_DB_CAMPUS_V2', '0.030', ''))
[Finished in 1.2s]

**Comment by fanlifei** [comment]
没有备份的问题解决了吗

**Comment by benben17** [comment]
需要执行主机开启binlog 的 ，没有binlog 就没有备份，不知道你的是不是这个问题
