### ISSUE TITLE
centos 7 编译报错

### ISSUE THREAD

**Issue by DavenAaron** [mysql-inception/inception#62]
Linking CXX executable mysql
../libmysql/libmysqlclient.a(net_serv.cc.o):(.note.stapsdt+0x24): undefined reference to `mysql_net__write__start_semaphore'
../libmysql/libmysqlclient.a(net_serv.cc.o):(.note.stapsdt+0x70): undefined reference to `mysql_net__write__done_semaphore'
../libmysql/libmysqlclient.a(net_serv.cc.o):(.note.stapsdt+0xbc): undefined reference to `mysql_net__write__done_semaphore'
../libmysql/libmysqlclient.a(net_serv.cc.o):(.note.stapsdt+0x108): undefined reference to `mysql_net__write__start_semaphore'
../libmysql/libmysqlclient.a(net_serv.cc.o):(.note.stapsdt+0x154): undefined reference to `mysql_net__write__done_semaphore'
../libmysql/libmysqlclient.a(net_serv.cc.o):(.note.stapsdt+0x1a0): undefined reference to `mysql_net__write__done_semaphore'
../libmysql/libmysqlclient.a(net_serv.cc.o):(.note.stapsdt+0x1ec): undefined reference to `mysql_net__read__start_semaphore'
../libmysql/libmysqlclient.a(net_serv.cc.o):(.note.stapsdt+0x230): undefined reference to `mysql_net__read__done_semaphore'
collect2: error: ld returned 1 exit status
make[2]: *** [client/mysql] Error 1
make[1]: *** [client/CMakeFiles/mysql.dir/all] Error 2
make: *** [all] Error 2

**Comment by slowtech** [comment]
我也遇到了这个问题，你这边解决了吗？

**Comment by cloudancer** [comment]
Centos7.4 x86_64上
yum install gcc gcc-c++ libgcc cmake ncurses openssl-devel
cmake版本2.8.12
wget http://ftp.gnu.org/gnu/bison/bison-2.5.1.tar.gz
tar zxvf bison-2.5.1.tar.gz
cd biso-2.5.1
./configure
make && make install
bison安装2.5.1版本后编译通过 :)
