### ISSUE TITLE
更新数据时报Execute Successfully,但是Backup failed，Error message 是： None 

### ISSUE THREAD

**Issue by AndyFan2017** [mysql-inception/inception#69]
更新数据时报Execute Successfully,但是Backup failed，Error message 是： None 
备份库中： $_$Inception_backup_information$_$ 信息有，并且也记录了 binlog位置，只是回滚语句没有生成。
有没有什么方式可以确定这个问题出在哪里？

**Comment by AndyFan2017** [comment]
原来是这个配置项的问题： binlog_row_image ,默认是 full， 如果是minimal 的话会导致生成不了rollback语句

**Comment by Vickey-Wu** [comment]
你好，binlog_row_image 这个在哪里设置啊
