### ISSUE TITLE
安装目录存在时，无法执行安装脚本！

### ISSUE THREAD

**Issue by yotoobo** [mysql-inception/inception#7]
脚本中对$debug_dir的判断中
if [ -d $debug_dir ]
then
  cd $debug_dir
else
如果目录已存在，则进入目录，但没有任何安装指令

**Comment by mysql-inception** [comment]
存在了不能删除，因为在编译之后，就可以不做cmake了，编译是可以继续的，所以在cmake出错之后，再次做build时，需要先删掉目录

**Comment by yotoobo** [comment]
thanks
